application: CapitalKnowledge
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:

- url: /helloworld.html
  script: helloworld.html

- url: /process.php
  script: process.php

- url: /csv.php
  script: csv.php
  
- url: /.*
  script: hello world.html
  

